### ISSUE TITLE
Crash and Aubrey Animation Glitch

### ISSUE THREAD

**Issue by BluffingRay** [rphsoftware/omori-web-port-patches#1]
Hi there, good day... I have just recently discover this patch and I am pretty late but anyway I just want to write this.

Btw, I am using Joiplay since it can emulate HTML games and I am at version 1.0.4.

The game boots up normally, and I was able to play the game like normal.

So, the animation glitch I found is that when Aubrey uses her bat and also smash, her animation glitches. (I've tried it both in Browser and Joiplay, and still the same)
![Screenshot_2021-04-01-11-51-28-683_com.android.chrome.jpg](https://user-images.githubusercontent.com/81332663/113246413-95047800-92eb-11eb-97c0-ab14c6f23378.jpg)

After playing some time I have also noticed that reading Joke Boards crashes the game (with this message).
![Screenshot_2021-04-01-11-08-30-863_cyou.joiplay.joiplay.jpg](https://user-images.githubusercontent.com/81332663/113246942-95514300-92ec-11eb-9534-2014409efc10.jpg)![Screenshot_2021-04-01-11-21-28-331_cyou.joiplay.joiplay.jpg](https://user-images.githubusercontent.com/81332663/113246953-984c3380-92ec-11eb-8afc-28d4576a917f.jpg)![Screenshot_2021-04-01-13-35-02-722_cyou.joiplay.joiplay.jpg](https://user-images.githubusercontent.com/81332663/113248388-76a07b80-92ef-11eb-91f4-fb0ed968fe82.jpg)

And Finally, when I have entered Pryefly Forest, it crashes (with this message) which makes it impossible to progress any further. 
![Screenshot_2021-04-01-11-03-10-576_cyou.joiplay.joiplay.jpg](https://user-images.githubusercontent.com/81332663/113247318-58398080-92ed-11eb-90a2-d7e0468dd045.jpg)

I was able to play The Prologue, Real World segment of 3 days left, and was able to access Orange Oasis.

So far, that's the only issues I've encountered and I was able to progress and play the game until Pryefly Forest.

Anyway, I am very thankful to you because I was able to play Omori on my android phone, even for a short while. Thank you very much.

**Comment by rphsoftware** [comment]
I am aware of most of these issues and I plan on repairing them when OMORI 1.0.8 comes out, since it apparently is supposed to be the final version, which will make porting it easier and more certain, that being said will keep this issue open for information purposes, thank you for taking interest in my project

**Comment by BluffingRay** [comment]
> I am aware of most of these issues and I plan on repairing them when OMORI 1.0.8 comes out, since it apparently is supposed to be the final version, which will make porting it easier and more certain, that being said will keep this issue open for information purposes, thank you for taking interest in my project

You're very welcome. You have my full support.

**Comment by thegreatestminer** [comment]
v1.0.8 is out.

**Comment by rphsoftware** [comment]
The [108 branch](https://github.com/rphsoftware/omori-web-port-patches/tree/108) now has a second version of the porting scripts.
Note that android on-screen controls support is missing, but it can now work with 1.0.8 (or any version past 1.0.1, in theory), and the bugs that originated this issue should also have been fixed.

**Comment by BluffingRay** [comment]
> The [108 branch](https://github.com/rphsoftware/omori-web-port-patches/tree/108) now has a second version of the porting scripts.
> Note that android on-screen controls support is missing, but it can now work with 1.0.8 (or any version past 1.0.1, in theory), and the bugs that originated this issue should also have been fixed.

Should I move the omori installation files? and what should be the name of the folder?
